version: "2.1"
services:
  #nginx 提供静态资源服务
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/shanghai
    volumes:
      - ./nginx/config:/config
    expose:
      - 80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`public.${DOMAIN}`)||Host(`ariang.${DOMAIN}`)"
      - "traefik.http.routers.nginx.entrypoints=web"

  #反向代理功能由 traefik 提供
  #traefik 能够自动发现和续期ssl，比用 nginx 反向代理写配置文件方便
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      #泛解析ssl配置
      - "--entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}"
      #证书申请配置，entrypoints.web的端口必须是80
      - "--certificatesresolvers.rr.acme.email=xx@xx.com"
      - "--certificatesresolvers.rr.acme.storage=acme.json"
      - "--certificatesresolvers.rr.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
  
        #old docker-compose
        #networks:
        #  default:
        #    external:
        #      name: traefik-net

networks:
  default:
    name: traefik-net
    external: true
